// https://img.yakkun.com/poke/icon96/n.gif
const POKEMONS = [
  {
    no: 149,
    name: "カイリュー",
    type1: "ドラゴン",
    type2: "ひこう",
    icon: "/icons/n149.gif",
    ability1: "せいしんりょく",
    ability2: "",
    ability3: "マルチスケイル",
    H: "91",
    A: "134",
    B: "95",
    C: "100",
    D: "100",
    S: "80",
  },
  {
    no: 637,
    name: "ウルガモス",
    type1: "ほのお",
    type2: "むし",
    icon: "/icons/n637.gif",
    ability1: "ほのおのからだ",
    ability2: "",
    ability3: "むしのしらせ",
    H: "85",
    A: "60",
    B: "65",
    C: "135",
    D: "105",
    S: "100",
  },
  {
    no: 983,
    name: "ハバタクカミ",
    type1: "ゴースト",
    type2: "フェアリー",
    icon: "/icons/n983.gif",
    ability1: "こだいかっせい",
    ability2: "",
    ability3: "",
    H: "55",
    A: "55",
    B: "55",
    C: "135",
    D: "135",
    S: "135",
  },
  {
    no: 1000,
    name: "サーフゴー",
    type1: "はがね",
    type2: "ゴースト",
    icon: "/icons/n977.gif",
    ability1: "おうごんのからだ",
    ability2: "",
    ability3: "",
    H: "87",
    A: "60",
    B: "95",
    C: "133",
    D: "91",
    S: "84",
  },
  {
    no: 1002,
    name: "パオジアン",
    type1: "あく",
    type2: "こおり",
    icon: "/icons/n995.gif",
    ability1: "わざわいのつるぎ",
    ability2: "",
    ability3: "",
    H: "80",
    A: "120",
    B: "80",
    C: "90",
    D: "65",
    S: "135",
  },
  {
    no: 1003,
    name: "ディンルー",
    type1: "あく",
    type2: "じめん",
    icon: "/icons/n994.gif",
    ability1: "わざわいのうつわ",
    ability2: "",
    ability3: "",
    H: "155",
    A: "110",
    B: "125",
    C: "55",
    D: "80",
    S: "45",
  },
] as const;
export default POKEMONS;
